first version. problem with station TypeError: check_for_trig() missing 1 required positional argument: 'station'. if i don't write it - no data everywhere